version: '3.8'

services:
  backend-api:
    build:
      context: ./backend/GemMarketplace.API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://backend-api/api"
    ports:
      - "3000:80"
    depends_on:
      - backend-api
